### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by raikasdev** [Nersent/wexond#622]
You have licensed this software under GPLv3, the PATENTS license is against the GPLv3 license as:
`To protect your rights, we need to prevent others from denying you these rights or asking you to surrender the rights. Therefore, you have certain responsibilities if you distribute copies of the software, or if you modify it: responsibilities to respect the freedom of others.`

You aren't allowed to do that, or your software isn't open source or licensed under GPLv3. The rights from GPLv3 apply, and you can't deny them with a another license.

**Comment by niilasoika** [comment]
+1

**Comment by Esinko** [comment]
+1
The rights granted by the GPLv3 license cannot be modified in any way to comply with the license standard.

**Comment by sentialx** [comment]
Since I'm the copyright holder, I can even cancel those clauses of GPL 3, because I'm in the control of how this project can be used. GPL 3 is just used as a template here to my custom license. Sorry, but I can no longer allow generating profits on my code.

**Comment by Esinko** [comment]
It's not about that you are in control, that's clear. You are just using the GPLv3 license incorrectly.
Edit: "...a template here to my custom license." If you are using a "custom" license, you cannot call it GPLv3, if nothing else, that should be corrected.

**Comment by raikasdev** [comment]
You call your project open source, which it is not in that case.
Also in your CLA you say that contributed code is licensed in GPLv3:
`In return, the General Developer shall reference you as a contributor to the open source code version of the Code Project that is currently distributed under the GNU General Public License (GPLv3).`.
So is the code licensed under GPLv3 or not?
License changes also cannot be enforced on older copies of the software.

**Comment by sentialx** [comment]
I removed the LICENSE and PATENTS files and put my own license in README file: https://github.com/wexond/browser-base#license

**Comment by EuriNaiz** [comment]
I just want to clarify the things.
1. GPLv3 give us the right to use patents, in fact that and the Anti-Tivoization were the improvements in respect to GPLv2
2. Guys, you CAN still USE the code non modified after the license removal, the GPL is not revocable.
3. You SHOULD delete all contributions done under the GPLv3, or ask the copyright rights, you cannot re-license the contributions, that code IS NOT your propriety. Do you want to change the license? Ok, Delete ALL the contributions because they are still under GPLv3 and YOU CANNOT CHANGE the license because YOU AREN'T the AUTHOR.
3. The GPL cannot be modified, you can use it as a template to create your own license, but you cannot call it GPL or suggest some affiliation with the GNU project or the Free Software Foundation
4. Consider using the GPLv2, it hasn't got the patents clause and the protections Anti-Tivoization, but it only applies for code that you own the copyright.
5. Guys, Don't allow relicence your commits, if you contribute a GPL proyect, your changes should keep under the GPL or removed.
6. Guys, please, use the Sysbase Open Watcom Public License, AGPLv3 or GPLv3, they are the safest licences, you can be sure that the software will keep Libre or at least Open.
7. Guys, remember, this software (excluding the 3rd commits, 3rd commits are GPLv3) are now closed source/proprietary software, please prefer other proyects like Firefox or DotHQ or WaterFox, they are still libres/open.

**Comment by ghost** [comment]
> I removed the LICENSE and PATENTS files and put my own license in README file: https://github.com/wexond/browser-base#license

So does that mean that we can't freely fork Wexond now? What about the already existent forks based on older source code?

**Comment by niilasoika** [comment]
Yes, some people I know have forked Wexond. Will they have to do something?

**Comment by nothingneko** [comment]
> Yes, some people I know have forked Wexond. Will they have to do something?

You should be ok if you forked before this, you just can't sync changes down anymore

**Comment by lleyton** [comment]
On a personal note, I find it disappointing to see where Wexond is going. For me, the browser base was helpful in the development of [Skye](https://github.com/skyebrowser/skye) and for many other projects like it. By close sourcing the software, the appeal for forks to upstream their fixes and changes back to Wexond is gone. I pose the question: is it worth killing the viability and community around this project in exchange for maintaining the exclusivity to generate an insignificant amount of profits? I say that it isn't.

**Comment by itslevir** [comment]
Close-sourcing an open source project? I smell a really bad idea.

**Comment by ghost** [comment]
> On a personal note, I find it disappointing to see where Wexond is going. For me, the browser base was helpful in the development of [Skye](https://github.com/skyebrowser/skye) and for many other projects like it. By close sourcing the software, the appeal for forks to upstream their fixes and changes back to Wexond is gone. I pose the question: is it worth killing the viability and community around this project in exchange for maintaining the exclusivity to generate an insignificant amount of profits? I say that it isn't.

Wexond is getting in an even worse direction. It's adding Google Analytics to its UI in the new closed-source version. I find it really disappointing. They're killing themselves.

**Comment by ghost** [comment]
> > Yes, some people I know have forked Wexond. Will they have to do something?
> 
> You should be ok if you forked before this, you just can't sync changes down anymore

You can also delete the latest commits when forking (those that include the license change) or contact the author.

**Comment by ghost** [comment]
The CLA contradicts the new LICENSE, too.

**Comment by jadeastar** [comment]
They deleted all Legal stuff, Skye has (what I think to be) the last GPL3 version. If you wanna contribute come on [over](github.com/skyebrowser)

**Comment by raikasdev** [comment]
The GPLv3 code can be viewed and downloaded: https://github.com/wexond/browser-base/tree/7064c8003b246ae62fb583a589128fb25932ab79

I also have a ZIP file if the link stops working, just contact me.

**Comment by nothingneko** [comment]
> The GPLv3 code can be viewed and downloaded: https://github.com/wexond/browser-base/tree/7064c8003b246ae62fb583a589128fb25932ab79
> 
> I also have a ZIP file if the link stops working, just contact me.

Here is a verbatim copy of the GPL for comparison
http://www.gnu.org/licenses/gpl-3.0.html

**Comment by ghost** [comment]
If the author of this repository changes the git history at any time, there are multiple ways to see the history.

**Comment by itslevir** [comment]
How about this. I'm going to quote the GPLv3.

```
"All rights granted under this License are ... irrevocable"
```
What you are doing is technically illegal.

**Comment by ghost** [comment]
> How about this. I'm going to quote the GPLv3.
> 
> ```
> "All rights granted under this License are ... irrevocable"
> ```
> 
> What you are doing is technically illegal.

We've sued them :D

**Comment by lerichardson** [comment]
> How about this. I'm going to quote the GPLv3.
> 
> ```
> "All rights granted under this License are ... irrevocable"
> ```
> What you are doing is technically illegal.

**Comment by niilasoika** [comment]
Why was a comment from @jadeastar deleted? I smell censorship xD

**Comment by sentialx** [comment]
We don't post cringe here, sir.

**Comment by nothingneko** [comment]
> Why was a comment from @jadeastar deleted? I smell censorship xD

Sussy

**Comment by raikasdev** [comment]
License can be changed if ALL code owners (including open source contributors, if CLA or similar doesn't make the code the project leaders) agree to it, as they are copyright owners.
The license can be changed for the future releases, but not for past. If you have a downloaded a version with a old license, it cannot be revoken.

**Comment by sentialx** [comment]
The list of people revoking license for old code:

**Comment by niilasoika** [comment]
I think that this issue should be reopened. Just because this hasn't been sorted out yet.

**Comment by ghost** [comment]
> License can be changed if ALL code owners (including open source contributors, if CLA or similar doesn't make the code the project leaders) agree to it, as they are copyright owners.
> The license can be changed for the future releases, but not for past. If you have a downloaded a version with a old license, it cannot be revoken.

Thanks for saying that. Sentialx is threatening to DMCA Skye and Gitpodium,
and has already done it with Dot Browser. He also has the intention to DMCA
midori, for some reason.

**Comment by ghost** [comment]
> I think that this issue should be reopened. Just because this hasn't been sorted out yet.

He won't do that :(

**Comment by raikasdev** [comment]
> 
> License can be changed if ALL code owners (including open source contributors, if CLA or similar doesn't make the code the project leaders) agree to it, as they are copyright owners. The license can be changed for the future releases, but not for past. If you have a downloaded a version with a old license, it cannot be revoken.
> Thanks for saying that. Sentialx is threatening to DMCA Skye and Gitpodium, and has already done it with Dot Browser. He also has the intention to DMCA midori, for some reason.

_Do you want to formally dispute the action by submitting a counter notice? Maybe the person sending the takedown notice does not hold the copyright or did not realize that you have a license or made some other mistake in their takedown notice. If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice. If you do, we will wait 10-14 days and then re-enable your content unless the copyright owner initiates a legal action before then._ (https://github.com/github/dmca)

https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-counter-notice

**Comment by raikasdev** [comment]
The code is licensed under GPLv3, he can't legally do that.

**Comment by ghost** [comment]
I don't know if he wants but I want! @sentialx last advertisement. We politely ask you yo revert your latest changes or we (the code owners) will take actions. You have 12 hours to revert the changes.
